### ISSUE TITLE
Review draft technical project plan

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#1]
Howdy @kidcompassion --

I've tried to summarize our conversation today, plus some notes from thinking this through over the last week or so [here in a GitHub repo for the project](https://github.com/TheTyee/buylocal.thetyee.ca).

Let me know if this is a clear enough plan for us to push forward with, and also if there are any details that could use more clarity. 

From there, I'd propose that we create some Milestones for where we need to be by when to get this launched in four weeks.

cc @MrBryan just so he's in the loop.

**Comment by phillipadsmith** [comment]
@kidcompassion Over to you to close this if it all makes sense! ;)

**Comment by kidcompassion** [comment]
I am, @phillipadsmith! Thanks for checking.
