### ISSUE TITLE
Remove this file

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#18]
@kidcompassion You've got some personal data (e-mails) in here:
https://github.com/TheTyee/buylocal.thetyee.ca/blob/master/_data/contests.csv

... shouldn't be committed to the repo.

That is what the entries.json was for, i.e., personal data removed.

**Comment by kidcompassion** [comment]
GAK! Thanks for catching it!

**Comment by phillipadsmith** [comment]
@kidcompassion Re-opening! ;)

See: https://help.github.com/articles/remove-sensitive-data/

**Comment by phillipadsmith** [comment]
Removed

**Comment by phillipadsmith** [comment]
If you're short on time / attention, I can fix that in the am. Lemme know! :-)

**Comment by kidcompassion** [comment]
Dammit! I should have known it wouldn't be as straightforward as deleting one file. _fail horn_ 
If you don't mind doing it, that would be awesome. The docs make me a bit nervous about how long it will take to figure it out and how much or a margin for error there is.

**Comment by phillipadsmith** [comment]
Yep, no worries. :-)

**Comment by MrBryan** [comment]
Go to bed, you two

**Comment by kidcompassion** [comment]
![9b38d4bc022432635175133af8298281c01bafe68e9eb10767e8a85dc41f9e13](https://cloud.githubusercontent.com/assets/1507827/11122574/0a9c5552-8919-11e5-990c-2e21e83959fb.jpg)

**Comment by phillipadsmith** [comment]
Okay, the file is purged! :-)
