### ISSUE TITLE
Setup Jekyll Hook so I can deploy

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#19]
I'd love to learn how to do this, @phillipadsmith - is there a way to leverage the housing fix setup to do this? Or is this too big a job for me to try to learn at this point?

**Comment by phillipadsmith** [comment]
> I'd love to learn how to do this, @phillipadsmith - is there a way to leverage the housing fix setup to do this? Or is this too big a job for me to try to learn at this point?

The housingifx instance of jekyll-hook is, unfortunately, jailed to the housingfix user. :-(

We'll need to think through where to set-up another instance for buylocal, and if we can possibly make it available to all our jekyll projects. 

Probably fastest for me to set it up this time, and I can then revisit the bigger question of making it available to more jekyll sites as we develop them.

**Comment by kidcompassion** [comment]
Okey doke. When there isn't a project looming, I'll spend some time trying to crack it too, so you're not the only one who understands it.

**Comment by phillipadsmith** [comment]
> Okey doke. When there isn't a project looming, I'll spend some time trying to crack it too, so you're not the only one who understands it.

That's one of the many things to get out of my head, and into yours on Monday/Tuesday! ;)

**Comment by phillipadsmith** [comment]
This is 90% done on the server, and yet I've got to run out for dinner & date night! Will need to finish this up tomorrow.

**Comment by phillipadsmith** [comment]
Okay! So this is up-and-running for the `develop` branch as it was/is for housingfix, i.e.,:
- Pushing to `develop` will deploy to http://develop.buylocal.thetyee.ca/ 
- If you add gems or bower-installed libraries, you'll need to ssh into the server under user `tyeeapps` and `rm -r -f` the ~/TheTyee/ directory, which will then force everything to re-install. (Just be aware that there are a bunch of other similarly-named directories under that user's home, so `rm -r -f` with caution!)

Few things I've noticed that might help:
- There are a lot of `http://localhost:4000` statements in the templates. Those are obviously not going to work when running on develop.buylocal.thetyee.ca. Best way around that is just to use relative paths to the resources, e.g., /assets/filename  which should be the same locally as remotely.
- If that won't work for some reason, you can always use a variable in your _config.development.yml that's different from your _config.yml (local vs. remote)
- There are a couple JS errors in the console.

Ping me if you have any questions. I'm around and working most of today. :-)

**Comment by phillipadsmith** [comment]
Quick update: I've moved that `TheTyee` directory under ~/github/ to make it easier to discern what's coming from GitHub.

**Comment by kidcompassion** [comment]
awesome! I just got the partner ads working correctly, so I can't wait to try this!

**Comment by kidcompassion** [comment]
@phillipadsmith one follow up question here, i'm having trouble pushing to development, and I'm not sure where to find the logs and/or the afforementioned ~/TheTyee/ directory. Can you send me a quick path in the next day or two? No rush, I'm going to head to bed and won't be home until about 2 PM PST.

**Comment by kidcompassion** [comment]
@phillipadsmith Disregard! I missed your earlier comment!
