### ISSUE TITLE
Touching up reader cards once they have live data

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#21]

**Comment by kidcompassion** [comment]
@phillipadsmith this is complete and merged into master, along with your latest updates. So I would say that it's in a place where Michelle can at least have a look at the functionality (I still have to integrate the ads, but what remains is pretty much all just CSS stuff.

**Comment by phillipadsmith** [comment]
> So I would say that it's in a place where Michelle can at least have a look at the functionality (I still have to integrate the ads, but what remains is pretty much all just CSS stuff.

Okay, I'm going to try to carve out an hour today to get this deployed to develop.buylocal.thetyee.ca and -- fingers crossed -- to set-up jekyll-hook to auto-deploy to that domain when you push to the 'develop' branch going forward. 

Will keep you updated. Leave it with me.  :-)
