### ISSUE TITLE
Hmmm... OAuth tokens?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#27]
I don't have an answer to this... but I'm wondering if it's common / considered secure to put OAuth tokens in a public config file [like so](https://github.com/TheTyee/buylocal.thetyee.ca/blob/master/_config.yml#L41)? 

I typically just run the `export GDRIVE ...` in my shell before running the `jekyll` command, just FYI.

**Comment by kidcompassion** [comment]
Removed from config.yml. Didn't bother purging it from Git.
