### ISSUE TITLE
Partner ad on the front page is broken.

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#28]
Question for you, @phillipadsmith!

On the home page, there should be just one orange partner ad loading beneath the cards, but it's broken. I'm guessing this is the result of moving the partner ads code into backbone; is there a way to extend it to handle for this orphan ad on the home page as well, or should i treat the home page as its own distinct entity? (That's what I did with the "recent cards" posted there, since I wanted them to behave differently.) 

![uploads/99941201-9155-425e-8629-12cb175c1323/Screen Shot 2015-11-15 at 1.19.50 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F99941201-9155-425e-8629-12cb175c1323%2FScreen+Shot+2015-11-15+at+1.19.50+PM.png)

**Comment by phillipadsmith** [comment]
@kidcompassion Got it! Will fix. :+1:

**Comment by phillipadsmith** [comment]
> is there a way to extend it to handle for this orphan ad on the home page as well, or should i treat the home page as its own distinct entity? (That's what I did with the "recent cards" posted there, since I wanted them to behave differently.)

Missed your question here... Yes, very easy to add it to the front page.

Is it a random promo? 

Will be as easy as inserting a App.promoView into the DOM at that location, passing in one of the models from the App.promos collection. 

Phillip.

**Comment by phillipadsmith** [comment]
Closed by #30
