### ISSUE TITLE
All cards are being rendered below the footer on the front page.

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#31]
The front page is perfect, except for that the letters page is being rendered below the footer.

**UPDATE***
I'm wrong, it's happening on all pages except /letters

**Comment by kidcompassion** [comment]
@phillipadsmith I've narrowed this down to

```
ul.append(new App.CardView({
                model: card
            }).render().el);
```

on line 176 of app.js, but I'm not sure how to resolve it! Can you help when you have time?

**Comment by phillipadsmith** [comment]
Yep, will fix. :-)
