### ISSUE TITLE
How to deploy to preview

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#35]
@kidcompassion 

Quick note:
- There's a preview branch now
- When you want to update the preview site, you can merge your develop branch into preview and push

That should deploy to preview, and develop will deploy to develop.

Just testing everything now. Appears to be working. Let me know if you have any questions.

Phillip.

**Comment by kidcompassion** [comment]
Closing this, since it's all working as expected.
