### ISSUE TITLE
Add analytics profile to main The Tyee analytics account

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#39]
Need to figure out what to do here... without input from Eric, I'm thinking we should just set-up the usual analytics vs. tag manager.

@kidcompassion Any thoughts? 

[Here's how we do it on Bottom Lines](https://github.com/TheTyee/bottom-lines/blob/master/ui/js/app.js#L418-L430) and it looks like in Backbone, and [in the page](https://github.com/TheTyee/bottom-lines/blob/e040de9d9234e798418d295422eaf450a468ba62/_includes/footer_scripts.html#L7-L18).

**Comment by kidcompassion** [comment]
Eric had me just put in GTM and a basic analytics set up for Housing Fix, because he said that was the best way to get started. I'll take care of this.

**Comment by phillipadsmith** [comment]
> I'll take care of this.

Awesome, thanks. Just keep in my that any of the Backbone "pages" are not really pages and won't send GA/GTM any data on their own (there's no page load per se), so you've got to add that logic to the Backbone router per example above.

**Comment by kidcompassion** [comment]
Moving this to review until I figure out how to check if it's firing.
