### ISSUE TITLE
Fix position of share buttons on cardDetailView

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#41]
<img width="359" alt="jj_bean" src="https://cloud.githubusercontent.com/assets/34128/11314671/84688048-8f9c-11e5-9a44-c7353811581f.png">

**Comment by kidcompassion** [comment]
same for this badboy. this should be in latest code in development.

**Comment by phillipadsmith** [comment]
:+1:
