### ISSUE TITLE
To avoid confusion, make this link relative?

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#43]
<img width="327" alt="buy_local" src="https://cloud.githubusercontent.com/assets/34128/11314746/5a39d7da-8f9d-11e5-942c-503566fcc0f8.png">

**Comment by phillipadsmith** [comment]
This one too?
<img width="324" alt="about" src="https://cloud.githubusercontent.com/assets/34128/11314755/7d0fd444-8f9d-11e5-98f6-3f4cc46c5ddb.png">

Just imagining M and others getting confused / reporting a problem.

**Comment by kidcompassion** [comment]
Google Docs wouldn't let me do a relative link using their UI, i so i just put in HTML. Not important, just writing myself a note so I remember how I did it.
