### ISSUE TITLE
Remove the (live) from the wufoo form in production, its coming up as the email subject

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#50]

**Comment by kidcompassion** [comment]
![uploads/154c2771-b431-4d37-9f88-576bb3ca4fac/Screen Shot 2015-11-22 at 4.00.12 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F154c2771-b431-4d37-9f88-576bb3ca4fac%2FScreen+Shot+2015-11-22+at+4.00.12+PM.png)

**Comment by phillipadsmith** [comment]
@kidcompassion Nice catch! :-)

**Comment by phillipadsmith** [comment]
Done
