### ISSUE TITLE
lettershow function doesn't fire in IE10

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#52]
All page paths in the router on line 418 in app.js work fine (the console.log message render, indicating that the correct functions fire.).

lettershow function does not run though, and it's the only route with a non-alphanumeric character (:). 

App.router.navigate(‘letters/show/[cardid]’, { trigger: true }) in the console creates a "invalid character error", but still loads the correct url in the url bar - but the corresponding function doesn't fire. I think it doesn't like the colon.

**Comment by kidcompassion** [comment]
![uploads/6883ebaa-b8f1-4ee9-b2c6-2dfdeb90d1c8/Screen Shot 2015-11-22 at 7.35.42 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6883ebaa-b8f1-4ee9-b2c6-2dfdeb90d1c8%2FScreen+Shot+2015-11-22+at+7.35.42+PM.png)

**Comment by kidcompassion** [comment]
![uploads/a8fc6d2b-7ff7-47c1-a404-51b644859342/Screen Shot 2015-11-22 at 7.24.48 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa8fc6d2b-7ff7-47c1-a404-51b644859342%2FScreen+Shot+2015-11-22+at+7.24.48+PM.png)

**Comment by phillipadsmith** [comment]
Hmmm... digging into it

**Comment by phillipadsmith** [comment]
Fixed with this commit:
https://github.com/TheTyee/buylocal.thetyee.ca/commit/7b38030d8cc83be2864de0980d9bbce60f4b96ae

(Not an IE issue)
