### ISSUE TITLE
Generating current url link in backbone for social media sharing

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#6]
@phillipadsmith I'm trying to figure out how to generate the social sharing links for the backbone cards. I understand how to retrieve them (history.getfragment()) but not so much how to successfully print them to the page. Any tips?

**Comment by phillipadsmith** [comment]
@kidcompassion You should be able to use their ID.

See: https://github.com/TheTyee/bottom-lines/blob/master/ui/js/app.js#L33-L57

**Comment by kidcompassion** [comment]
Thank you!
