### ISSUE TITLE
Display a partner ad every 9 or 12 cards on the "all letters" page

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#7]
As per the old site, I need to surface a partner ad every 9 or 12 cards. not sure of best way to handle this in backbone. My plan is to just inject them in with jquery.

**Comment by kidcompassion** [comment]
@phillipadsmith just an update; I've got everything working as desired except the social sharing. I have to pack and everything for tomorrow, but I'll be working throughout the day and when I get to town so this can be in full test and beta for Monday.

**Comment by kidcompassion** [comment]
@phillipadsmith also, the cards on the index are not done in backbone; I did them in jQuery in the interest of time since I wanted them to behave differently than the ones on the letters page (it felt weird to surface a single card on the front page, I'd rather push people to the full letters page).

**Comment by phillipadsmith** [comment]
> I've got everything working as desired except the social sharing. I have to pack and everything for tomorrow, but I'll be working throughout the day and when I get to town so this can be in full test and beta for Monday.

Cool. I'm working today and tomorrow -- catch-up & prep for your visit -- so just let me know where you leave off and I'll invest a couple hours in pushing things forward. Happy to take social sharing off your hands, if that's the easiest.

> also, the cards on the index are not done in backbone; I did them in jQuery in the interest of time since I wanted them to behave differently than the ones on the letters page (it felt weird to surface a single card on the front page, I'd rather push people to the full letters page).

Cool. Probably fine for now. I'll take a quick look.
